# Generated by Django 2.2 on 2019-06-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Viewing date')),
                ('visibility', models.CharField(choices=[('C', 'Clear'), ('P', 'Partial'), ('O', 'Obscured')], default='C', max_length=1)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Star')),
            ],
        ),
    ]
