# Generated by Django 2.2 on 2019-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_viewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='date',
            field=models.DateField(verbose_name='Viewing date'),
        ),
    ]
