# Generated by Django 2.2 on 2019-06-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190612_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewing',
            options={'ordering': ['-date']},
        ),
    ]
