# Generated by Django 2.2 on 2019-06-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_observatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='observatories',
            field=models.ManyToManyField(to='main_app.Observatory'),
        ),
    ]
